In [1]:
import pandas as pd

In [3]:
mydata = pd.read_csv("https://github.com/deepanshu88/Datasets/raw/master/UploadedFiles/income.csv")
mydata

,Index,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
0,A,Alabama,1296530,1317711,1118631,1492583,1107408,1440134,1945229,1944173,1237582,1440756,1186741,1852841,1558906,1916661
1,A,Alaska,1170302,1960378,1818085,1447852,1861639,1465841,1551826,1436541,1629616,1230866,1512804,1985302,1580394,1979143
2,A,Arizona,1742027,1968140,1377583,1782199,1102568,1109382,1752886,1554330,1300521,1130709,1907284,1363279,1525866,1647724
3,A,Arkansas,1485531,1994927,1119299,1947979,1669191,1801213,1188104,1628980,1669295,1928238,1216675,1591896,1360959,1329341
4,C,California,1685349,1675807,1889570,1480280,1735069,1812546,1487315,1663809,1624509,1639670,1921845,1156536,1388461,1644607
5,C,Colorado,1343824,1878473,1886149,1236697,1871471,1814218,1875146,1752387,1913275,1665877,1491604,1178355,1383978,1330736
6,C,Connecticut,1610512,1232844,1181949,1518933,1841266,1976976,1764457,1972730,1968730,1945524,1228529,1582249,1503156,1718072
7,D,Delaware,1330403,1268673,1706751,1403759,1441351,1300836,1762096,1553585,1370984,1318669,1984027,1671279,1803169,1627508
8,D,District of Columbia,1111437,1993741,1374643,1827949,1803852,1595981,1193245,1739748,1707823,1353449,1979708,1912654,1782169,1410183
9,F,Florida,1964626,1468852,1419738,1362787,1339608,1278550,1756185,1818438,1198403,1497051,1131928,1107448,1407784,1170389
10,G,Georgia,1929009,1541565,1810773,1779091,1326846,1223770,1773090,1630325,1145473,1851245,1850111,1887157,1259353,1725470
11,H,Hawaii,1461570,1200280,1213993,1245931,1459383,1430465,1919423,1928416,1330509,1902816,1695126,1517184,1948108,1150882
12,I,Idaho,1353210,1438538,1739154,1541015,1122387,1772050,1335481,1748608,1436809,1456340,1643855,1312561,1713718,1757171
13,I,Illinois,1508356,1527440,1493029,1261353,1540274,1747614,1871645,1658551,1422021,1751422,1696729,1915435,1645465,1583516
14,I,Indiana,1776918,1734104,1269927,1204117,1848073,1129546,1139551,1883976,1999102,1559924,1905760,1129794,1988394,1467614
15,I,Iowa,1499269,1444576,1576367,1388924,1554813,1452911,1317983,1150783,1751389,1992996,1501879,1173694,1431705,1641866
16,K,Kansas,1509054,1290700,1522230,1532094,1104256,1863278,1949478,1561528,1550433,1465812,1882929,1410249,1930090,1385528
17,K,Kentucky,1813878,1448846,1800760,1250524,1137913,1911227,1301848,1956681,1350895,1512894,1916616,1878271,1722762,1913350
18,L,Louisiana,1584734,1110625,1868456,1751920,1233709,1920301,1185085,1124853,1498662,1210385,1234234,1287663,1908602,1403857
19,M,Maine,1582720,1678622,1208496,1912040,1438549,1330014,1295877,1969163,1627262,1706080,1437088,1318546,1116792,1529233
20,M,Maryland,1579713,1404700,1849798,1397738,1310270,1789128,1112765,1967225,1486246,1872327,1175819,1314343,1979529,1569566
21,M,Massachusetts,1647582,1686259,1620601,1777250,1531641,1380529,1978904,1567651,1761048,1658538,1482203,1731917,1669749,1963337
22,M,Michigan,1295635,1149931,1601027,1340716,1729449,1567494,1990431,1575185,1267626,1274673,1709853,1815596,1965196,1646634
23,M,Minnesota,1729921,1675204,1903907,1561839,1985692,1148621,1328133,1890633,1995304,1575533,1910216,1972021,1515366,1864553
24,M,Mississippi,1983285,1292558,1631325,1943311,1354579,1731643,1428291,1568049,1383227,1629132,1988270,1907777,1649668,1991232
25,M,Missouri,1221316,1858368,1773451,1573967,1374863,1486197,1735099,1800620,1164202,1425363,1800052,1698105,1767835,1996005
26,M,Montana,1877154,1540099,1332722,1273327,1625721,1983568,1251742,1592690,1350619,1520064,1185225,1465705,1110394,1125903
27,N,Nebraska,1885081,1309769,1425527,1240465,1500594,1278272,1140598,1270585,1128711,1187207,1569665,1690920,1459243,1802211
28,N,Nevada,1426117,1114500,1119707,1758830,1694526,1765826,1903270,1231480,1526066,1143343,1980195,1283813,1225348,1903804
29,N,New Hampshire,1419776,1854370,1195119,1990062,1645430,1286967,1762936,1763211,1265642,1704297,1131298,1197576,1242623,1963313
30,N,New Jersey,1605532,1141514,1613550,1181452,1541327,1156804,1568034,1357418,1443718,1390010,1202326,1100990,1850165,1183568
31,N,New Mexico,1819239,1226057,1935991,1124400,1723493,1475985,1237704,1820856,1801430,1653384,1475715,1623388,1533494,1868612
32,N,New York,1395149,1611371,1170675,1446810,1426941,1463171,1732098,1426216,1604531,1683687,1500089,1718837,1619033,1367705
33,N,North Carolina,1616742,1292223,1482792,1532347,1158716,1827420,1267737,1116168,1791535,1553750,1472258,1104893,1596452,1229085
34,N,North Dakota,1618807,1510193,1876940,1443172,1425030,1868788,1720352,1671468,1534571,1271132,1430978,1529024,1563898,1604118
35,O,Ohio,1802132,1648498,1441386,1670280,1534888,1314824,1516621,1511460,1585465,1887714,1227303,1840898,1880804,1573117
36,O,Oklahoma,1173918,1334639,1663622,1798714,1312574,1708245,1256746,1853142,1673831,1822933,1674707,1900523,1956742,1307678
37,O,Oregon,1794912,1726665,1805445,1133510,1502242,1419251,1482786,1862351,1103794,1935687,1905378,1522129,1509171,1893515
38,P,Pennsylvania,1320191,1446723,1218591,1122030,1971479,1563062,1274168,1571032,1433835,1483292,1290329,1475344,1931500,1668232
39,R,Rhode Island,1501744,1942942,1266657,1961923,1835983,1234040,1151409,1993136,1983569,1781016,1909119,1531212,1990412,1611730
40,S,South Carolina,1631522,1803455,1425193,1458191,1538731,1825195,1250499,1864685,1345102,1116203,1532332,1591735,1188417,1110655
41,S,South Dakota,1159037,1150689,1660148,1417141,1418586,1279134,1171870,1852424,1554782,1647245,1811156,1147488,1302834,1136443
42,T,Tennessee,1811867,1485909,1974179,1157059,1786132,1399191,1826406,1326460,1231739,1469785,1849041,1560887,1349173,1162164
43,T,Texas,1520591,1310777,1957713,1907326,1873544,1655483,1785986,1827503,1447457,1978374,1882532,1698698,1646508,1705322
44,U,Utah,1771096,1195861,1979395,1241662,1437456,1859416,1939284,1915865,1619186,1288285,1108281,1123353,1801019,1729273
45,V,Vermont,1146902,1832249,1492704,1579265,1332048,1563537,1123567,1618583,1326369,1792600,1714960,1146278,1282790,1565924
46,V,Virginia,1134317,1163996,1891068,1853855,1708715,1197698,1803330,1590043,1516758,1171686,1262342,1647032,1706707,1850394
47,W,Washington,1977749,1687136,1199490,1163092,1334864,1621989,1545621,1555554,1179331,1150089,1775787,1273834,1387428,1377341
48,W,West Virginia,1677347,1380662,1176100,1888948,1922085,1740826,1238174,1539322,1539603,1872519,1462137,1683127,1204344,1198791
49,W,Wisconsin,1788920,1518578,1289663,1436888,1251678,1721874,1980167,1901394,1648755,1940943,1729177,1510119,1701650,1846238
50,W,Wyoming,1775190,1498098,1198212,1881688,1750527,1523124,1587602,1504455,1282142,1881814,1673668,1994022,1204029,1853858

In [8]:
mydata.columns      #list of columns in df
# mydata.columns[0:2]  #specific columns in df

Index(['Index', 'State', 'Y2002', 'Y2003', 'Y2004', 'Y2005', 'Y2006', 'Y2007',
       'Y2008', 'Y2009', 'Y2010', 'Y2011', 'Y2012', 'Y2013', 'Y2014', 'Y2015'],
      dtype='object')

In [ ]:
mydata.dtypes #types of variables in df, object = string
mydata['State'].dtype  #type of specific column, 'O' = object = string

dtype('O')

In [9]:
mydata.Y2008 = mydata.Y2008.astype(float) #change type of specific column
mydata.dtypes

Index     object
State     object
Y2002      int64
Y2003      int64
Y2004      int64
Y2005      int64
Y2006      int64
Y2007      int64
Y2008    float64
Y2009      int64
Y2010      int64
Y2011      int64
Y2012      int64
Y2013      int64
Y2014      int64
Y2015      int64
dtype: object

In [ ]:
mydata.shape #rows, columns

(51, 16)

In [ ]:
mydata.shape[0] #number of rows
mydata.shape[1] #number of columns

51

In [ ]:
mydata.head() #first 5 rows

,Index,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
0,A,Alabama,1296530,1317711,1118631,1492583,1107408,1440134,1945229.0,1944173,1237582,1440756,1186741,1852841,1558906,1916661
1,A,Alaska,1170302,1960378,1818085,1447852,1861639,1465841,1551826.0,1436541,1629616,1230866,1512804,1985302,1580394,1979143
2,A,Arizona,1742027,1968140,1377583,1782199,1102568,1109382,1752886.0,1554330,1300521,1130709,1907284,1363279,1525866,1647724
3,A,Arkansas,1485531,1994927,1119299,1947979,1669191,1801213,1188104.0,1628980,1669295,1928238,1216675,1591896,1360959,1329341
4,C,California,1685349,1675807,1889570,1480280,1735069,1812546,1487315.0,1663809,1624509,1639670,1921845,1156536,1388461,1644607

In [ ]:
mydata.tail() #last 5 rows

,Index,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
46,V,Virginia,1134317,1163996,1891068,1853855,1708715,1197698,1803330.0,1590043,1516758,1171686,1262342,1647032,1706707,1850394
47,W,Washington,1977749,1687136,1199490,1163092,1334864,1621989,1545621.0,1555554,1179331,1150089,1775787,1273834,1387428,1377341
48,W,West Virginia,1677347,1380662,1176100,1888948,1922085,1740826,1238174.0,1539322,1539603,1872519,1462137,1683127,1204344,1198791
49,W,Wisconsin,1788920,1518578,1289663,1436888,1251678,1721874,1980167.0,1901394,1648755,1940943,1729177,1510119,1701650,1846238
50,W,Wyoming,1775190,1498098,1198212,1881688,1750527,1523124,1587602.0,1504455,1282142,1881814,1673668,1994022,1204029,1853858

In [ ]:
s = pd.Series([1, 3, 5, 7, 9], dtype = "category") #create a categorical series
s.dtype

CategoricalDtype(categories=[1, 3, 5, 7, 9], ordered=False, categories_dtype=int64)

In [ ]:
mydata.Index.unique() #unique values in a column(Index)

array(['A', 'C', 'D', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'O', 'P',
       'R', 'S', 'T', 'U', 'V', 'W'], dtype=object)

In [ ]:
mydata.Index.nunique() #number of unique values in a column(Index)

19

In [ ]:
pd.crosstab(mydata.Index,mydata.State) #cross tabulation of two columns

State,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
Index,,,,,,,,,,,,,,,,,,,,,
A,1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C,0,0,0,0,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
D,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
F,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
G,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
H,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
I,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
K,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
M,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
N,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
P,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
R,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
S,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
T,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
U,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
V,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
W,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,1

In [22]:
mydata.Index.value_counts(ascending = True) #frequency distribution of values in a column(Index)

Index
F    1
G    1
H    1
L    1
P    1
R    1
U    1
K    2
T    2
S    2
V    2
D    2
C    3
O    3
I    4
A    4
W    4
N    8
M    8
Name: count, dtype: int64

In [24]:
mydata.sample(5) #random sample of 5 rows

,Index,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
4,C,California,1685349,1675807,1889570,1480280,1735069,1812546,1487315.0,1663809,1624509,1639670,1921845,1156536,1388461,1644607
21,M,Massachusetts,1647582,1686259,1620601,1777250,1531641,1380529,1978904.0,1567651,1761048,1658538,1482203,1731917,1669749,1963337
23,M,Minnesota,1729921,1675204,1903907,1561839,1985692,1148621,1328133.0,1890633,1995304,1575533,1910216,1972021,1515366,1864553
48,W,West Virginia,1677347,1380662,1176100,1888948,1922085,1740826,1238174.0,1539322,1539603,1872519,1462137,1683127,1204344,1198791
0,A,Alabama,1296530,1317711,1118631,1492583,1107408,1440134,1945229.0,1944173,1237582,1440756,1186741,1852841,1558906,1916661

In [25]:
mydata.sample(frac = 0.1) #random sample of 10% of rows

,Index,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
41,S,South Dakota,1159037,1150689,1660148,1417141,1418586,1279134,1171870.0,1852424,1554782,1647245,1811156,1147488,1302834,1136443
14,I,Indiana,1776918,1734104,1269927,1204117,1848073,1129546,1139551.0,1883976,1999102,1559924,1905760,1129794,1988394,1467614
15,I,Iowa,1499269,1444576,1576367,1388924,1554813,1452911,1317983.0,1150783,1751389,1992996,1501879,1173694,1431705,1641866
50,W,Wyoming,1775190,1498098,1198212,1881688,1750527,1523124,1587602.0,1504455,1282142,1881814,1673668,1994022,1204029,1853858
31,N,New Mexico,1819239,1226057,1935991,1124400,1723493,1475985,1237704.0,1820856,1801430,1653384,1475715,1623388,1533494,1868612

In [26]:
mydata.State #specific column
mydata[['State','Index']] #specific columns
mydata["State"]

0                  Alabama
1                   Alaska
2                  Arizona
3                 Arkansas
4               California
5                 Colorado
6              Connecticut
7                 Delaware
8     District of Columbia
9                  Florida
10                 Georgia
11                  Hawaii
12                   Idaho
13                Illinois
14                 Indiana
15                    Iowa
16                  Kansas
17                Kentucky
18               Louisiana
19                   Maine
20                Maryland
21           Massachusetts
22                Michigan
23               Minnesota
24             Mississippi
25                Missouri
26                 Montana
27                Nebraska
28                  Nevada
29           New Hampshire
30              New Jersey
31              New Mexico
32                New York
33          North Carolina
34            North Dakota
35                    Ohio
36                Oklahoma
37                  Oregon
38            Pennsylvania
39            Rhode Island
40          South Carolina
41            South Dakota
42               Tennessee
43                   Texas
44                    Utah
45                 Vermont
46                Virginia
47              Washington
48           West Virginia
49               Wisconsin
50                 Wyoming
Name: State, dtype: object

In [27]:
mydata.loc[:,["Index","State","Y2008"]]
mydata.loc[0:2,["Index","State","Y2008"]] #Selecting rows with Index label 0 to 2 & columns
mydata.loc[:,"Index":"Y2008"] #Selecting consecutive columns
#In the above command both Index and Y2008 are included.
mydata.iloc[:,0:5] #Columns from 1 to 5 are included. 6th column not included

   Index                 State    Y2002    Y2003    Y2004
0      A               Alabama  1296530  1317711  1118631
1      A                Alaska  1170302  1960378  1818085
2      A               Arizona  1742027  1968140  1377583
3      A              Arkansas  1485531  1994927  1119299
4      C            California  1685349  1675807  1889570
5      C              Colorado  1343824  1878473  1886149
6      C           Connecticut  1610512  1232844  1181949
7      D              Delaware  1330403  1268673  1706751
8      D  District of Columbia  1111437  1993741  1374643
9      F               Florida  1964626  1468852  1419738
10     G               Georgia  1929009  1541565  1810773
11     H                Hawaii  1461570  1200280  1213993
12     I                 Idaho  1353210  1438538  1739154
13     I              Illinois  1508356  1527440  1493029
14     I               Indiana  1776918  1734104  1269927
15     I                  Iowa  1499269  1444576  1576367
16     K                Kansas  1509054  1290700  1522230
17     K              Kentucky  1813878  1448846  1800760
18     L             Louisiana  1584734  1110625  1868456
19     M                 Maine  1582720  1678622  1208496
20     M              Maryland  1579713  1404700  1849798
21     M         Massachusetts  1647582  1686259  1620601
22     M              Michigan  1295635  1149931  1601027
23     M             Minnesota  1729921  1675204  1903907
24     M           Mississippi  1983285  1292558  1631325
25     M              Missouri  1221316  1858368  1773451
26     M               Montana  1877154  1540099  1332722
27     N              Nebraska  1885081  1309769  1425527
28     N                Nevada  1426117  1114500  1119707
29     N         New Hampshire  1419776  1854370  1195119
30     N            New Jersey  1605532  1141514  1613550
31     N            New Mexico  1819239  1226057  1935991
32     N              New York  1395149  1611371  1170675
33     N        North Carolina  1616742  1292223  1482792
34     N          North Dakota  1618807  1510193  1876940
35     O                  Ohio  1802132  1648498  1441386
36     O              Oklahoma  1173918  1334639  1663622
37     O                Oregon  1794912  1726665  1805445
38     P          Pennsylvania  1320191  1446723  1218591
39     R          Rhode Island  1501744  1942942  1266657
40     S        South Carolina  1631522  1803455  1425193
41     S          South Dakota  1159037  1150689  1660148
42     T             Tennessee  1811867  1485909  1974179
43     T                 Texas  1520591  1310777  1957713
44     U                  Utah  1771096  1195861  1979395
45     V               Vermont  1146902  1832249  1492704
46     V              Virginia  1134317  1163996  1891068
47     W            Washington  1977749  1687136  1199490
48     W         West Virginia  1677347  1380662  1176100
49     W             Wisconsin  1788920  1518578  1289663
50     W               Wyoming  1775190  1498098  1198212

In [ ]:
mydata.set_index("Index",inplace = True) #setting Index column as index of df
mydata.head()
#Note that the indices have changed and Index column is now no more a column
mydata.columns
mydata.reset_index(inplace = True) #resetting index to default integer index
mydata.head()

,Index,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
0,A,Alabama,1296530,1317711,1118631,1492583,1107408,1440134,1945229.0,1944173,1237582,1440756,1186741,1852841,1558906,1916661
1,A,Alaska,1170302,1960378,1818085,1447852,1861639,1465841,1551826.0,1436541,1629616,1230866,1512804,1985302,1580394,1979143
2,A,Arizona,1742027,1968140,1377583,1782199,1102568,1109382,1752886.0,1554330,1300521,1130709,1907284,1363279,1525866,1647724
3,A,Arkansas,1485531,1994927,1119299,1947979,1669191,1801213,1188104.0,1628980,1669295,1928238,1216675,1591896,1360959,1329341
4,C,California,1685349,1675807,1889570,1480280,1735069,1812546,1487315.0,1663809,1624509,1639670,1921845,1156536,1388461,1644607

In [ ]:
mydata.drop('Index',axis = 1) #By default axis = 0 which means the operation should take place horizontally, row wise. To remove a column we need to set axis = 1.
#Alternatively
mydata.drop("Index",axis = "columns")
mydata.drop(['Index','State'],axis = 1)
mydata.drop(0,axis = 0)
mydata.drop(0,axis = "index")
mydata.drop([0,1,2,3],axis = 0)

,Index,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
4,C,California,1685349,1675807,1889570,1480280,1735069,1812546,1487315.0,1663809,1624509,1639670,1921845,1156536,1388461,1644607
5,C,Colorado,1343824,1878473,1886149,1236697,1871471,1814218,1875146.0,1752387,1913275,1665877,1491604,1178355,1383978,1330736
6,C,Connecticut,1610512,1232844,1181949,1518933,1841266,1976976,1764457.0,1972730,1968730,1945524,1228529,1582249,1503156,1718072
7,D,Delaware,1330403,1268673,1706751,1403759,1441351,1300836,1762096.0,1553585,1370984,1318669,1984027,1671279,1803169,1627508
8,D,District of Columbia,1111437,1993741,1374643,1827949,1803852,1595981,1193245.0,1739748,1707823,1353449,1979708,1912654,1782169,1410183
9,F,Florida,1964626,1468852,1419738,1362787,1339608,1278550,1756185.0,1818438,1198403,1497051,1131928,1107448,1407784,1170389
10,G,Georgia,1929009,1541565,1810773,1779091,1326846,1223770,1773090.0,1630325,1145473,1851245,1850111,1887157,1259353,1725470
11,H,Hawaii,1461570,1200280,1213993,1245931,1459383,1430465,1919423.0,1928416,1330509,1902816,1695126,1517184,1948108,1150882
12,I,Idaho,1353210,1438538,1739154,1541015,1122387,1772050,1335481.0,1748608,1436809,1456340,1643855,1312561,1713718,1757171
13,I,Illinois,1508356,1527440,1493029,1261353,1540274,1747614,1871645.0,1658551,1422021,1751422,1696729,1915435,1645465,1583516
14,I,Indiana,1776918,1734104,1269927,1204117,1848073,1129546,1139551.0,1883976,1999102,1559924,1905760,1129794,1988394,1467614
15,I,Iowa,1499269,1444576,1576367,1388924,1554813,1452911,1317983.0,1150783,1751389,1992996,1501879,1173694,1431705,1641866
16,K,Kansas,1509054,1290700,1522230,1532094,1104256,1863278,1949478.0,1561528,1550433,1465812,1882929,1410249,1930090,1385528
17,K,Kentucky,1813878,1448846,1800760,1250524,1137913,1911227,1301848.0,1956681,1350895,1512894,1916616,1878271,1722762,1913350
18,L,Louisiana,1584734,1110625,1868456,1751920,1233709,1920301,1185085.0,1124853,1498662,1210385,1234234,1287663,1908602,1403857
19,M,Maine,1582720,1678622,1208496,1912040,1438549,1330014,1295877.0,1969163,1627262,1706080,1437088,1318546,1116792,1529233
20,M,Maryland,1579713,1404700,1849798,1397738,1310270,1789128,1112765.0,1967225,1486246,1872327,1175819,1314343,1979529,1569566
21,M,Massachusetts,1647582,1686259,1620601,1777250,1531641,1380529,1978904.0,1567651,1761048,1658538,1482203,1731917,1669749,1963337
22,M,Michigan,1295635,1149931,1601027,1340716,1729449,1567494,1990431.0,1575185,1267626,1274673,1709853,1815596,1965196,1646634
23,M,Minnesota,1729921,1675204,1903907,1561839,1985692,1148621,1328133.0,1890633,1995304,1575533,1910216,1972021,1515366,1864553
24,M,Mississippi,1983285,1292558,1631325,1943311,1354579,1731643,1428291.0,1568049,1383227,1629132,1988270,1907777,1649668,1991232
25,M,Missouri,1221316,1858368,1773451,1573967,1374863,1486197,1735099.0,1800620,1164202,1425363,1800052,1698105,1767835,1996005
26,M,Montana,1877154,1540099,1332722,1273327,1625721,1983568,1251742.0,1592690,1350619,1520064,1185225,1465705,1110394,1125903
27,N,Nebraska,1885081,1309769,1425527,1240465,1500594,1278272,1140598.0,1270585,1128711,1187207,1569665,1690920,1459243,1802211
28,N,Nevada,1426117,1114500,1119707,1758830,1694526,1765826,1903270.0,1231480,1526066,1143343,1980195,1283813,1225348,1903804
29,N,New Hampshire,1419776,1854370,1195119,1990062,1645430,1286967,1762936.0,1763211,1265642,1704297,1131298,1197576,1242623,1963313
30,N,New Jersey,1605532,1141514,1613550,1181452,1541327,1156804,1568034.0,1357418,1443718,1390010,1202326,1100990,1850165,1183568
31,N,New Mexico,1819239,1226057,1935991,1124400,1723493,1475985,1237704.0,1820856,1801430,1653384,1475715,1623388,1533494,1868612
32,N,New York,1395149,1611371,1170675,1446810,1426941,1463171,1732098.0,1426216,1604531,1683687,1500089,1718837,1619033,1367705
33,N,North Carolina,1616742,1292223,1482792,1532347,1158716,1827420,1267737.0,1116168,1791535,1553750,1472258,1104893,1596452,1229085
34,N,North Dakota,1618807,1510193,1876940,1443172,1425030,1868788,1720352.0,1671468,1534571,1271132,1430978,1529024,1563898,1604118
35,O,Ohio,1802132,1648498,1441386,1670280,1534888,1314824,1516621.0,1511460,1585465,1887714,1227303,1840898,1880804,1573117
36,O,Oklahoma,1173918,1334639,1663622,1798714,1312574,1708245,1256746.0,1853142,1673831,1822933,1674707,1900523,1956742,1307678
37,O,Oregon,1794912,1726665,1805445,1133510,1502242,1419251,1482786.0,1862351,1103794,1935687,1905378,1522129,1509171,1893515
38,P,Pennsylvania,1320191,1446723,1218591,1122030,1971479,1563062,1274168.0,1571032,1433835,1483292,1290329,1475344,1931500,1668232
39,R,Rhode Island,1501744,1942942,1266657,1961923,1835983,1234040,1151409.0,1993136,1983569,1781016,1909119,1531212,1990412,1611730
40,S,South Carolina,1631522,1803455,1425193,1458191,1538731,1825195,1250499.0,1864685,1345102,1116203,1532332,1591735,1188417,1110655
41,S,South Dakota,1159037,1150689,1660148,1417141,1418586,1279134,1171870.0,1852424,1554782,1647245,1811156,1147488,1302834,1136443
42,T,Tennessee,1811867,1485909,1974179,1157059,1786132,1399191,1826406.0,1326460,1231739,1469785,1849041,1560887,1349173,1162164
43,T,Texas,1520591,1310777,1957713,1907326,1873544,1655483,1785986.0,1827503,1447457,1978374,1882532,1698698,1646508,1705322
44,U,Utah,1771096,1195861,1979395,1241662,1437456,1859416,1939284.0,1915865,1619186,1288285,1108281,1123353,1801019,1729273
45,V,Vermont,1146902,1832249,1492704,1579265,1332048,1563537,1123567.0,1618583,1326369,1792600,1714960,1146278,1282790,1565924
46,V,Virginia,1134317,1163996,1891068,1853855,1708715,1197698,1803330.0,1590043,1516758,1171686,1262342,1647032,1706707,1850394
47,W,Washington,1977749,1687136,1199490,1163092,1334864,1621989,1545621.0,1555554,1179331,1150089,1775787,1273834,1387428,1377341
48,W,West Virginia,1677347,1380662,1176100,1888948,1922085,1740826,1238174.0,1539322,1539603,1872519,1462137,1683127,1204344,1198791
49,W,Wisconsin,1788920,1518578,1289663,1436888,1251678,1721874,1980167.0,1901394,1648755,1940943,1729177,1510119,1701650,1846238
50,W,Wyoming,1775190,1498098,1198212,1881688,1750527,1523124,1587602.0,1504455,1282142,1881814,1673668,1994022,1204029,1853858

In [31]:
mydata.sort_values("State",ascending = False)
mydata.sort_values("State",ascending = False,inplace = True)
mydata.Y2006.sort_values()

2     1102568
16    1104256
0     1107408
12    1122387
17    1137913
33    1158716
18    1233709
49    1251678
20    1310270
36    1312574
10    1326846
45    1332048
47    1334864
9     1339608
24    1354579
25    1374863
41    1418586
34    1425030
32    1426941
44    1437456
19    1438549
7     1441351
11    1459383
27    1500594
37    1502242
21    1531641
35    1534888
40    1538731
13    1540274
30    1541327
15    1554813
26    1625721
29    1645430
3     1669191
28    1694526
46    1708715
31    1723493
22    1729449
4     1735069
50    1750527
42    1786132
8     1803852
39    1835983
6     1841266
14    1848073
1     1861639
5     1871471
43    1873544
48    1922085
38    1971479
23    1985692
Name: Y2006, dtype: int64

In [32]:
mydata.sort_values(["Index","Y2002"])

,Index,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
1,A,Alaska,1170302,1960378,1818085,1447852,1861639,1465841,1551826.0,1436541,1629616,1230866,1512804,1985302,1580394,1979143
0,A,Alabama,1296530,1317711,1118631,1492583,1107408,1440134,1945229.0,1944173,1237582,1440756,1186741,1852841,1558906,1916661
3,A,Arkansas,1485531,1994927,1119299,1947979,1669191,1801213,1188104.0,1628980,1669295,1928238,1216675,1591896,1360959,1329341
2,A,Arizona,1742027,1968140,1377583,1782199,1102568,1109382,1752886.0,1554330,1300521,1130709,1907284,1363279,1525866,1647724
5,C,Colorado,1343824,1878473,1886149,1236697,1871471,1814218,1875146.0,1752387,1913275,1665877,1491604,1178355,1383978,1330736
6,C,Connecticut,1610512,1232844,1181949,1518933,1841266,1976976,1764457.0,1972730,1968730,1945524,1228529,1582249,1503156,1718072
4,C,California,1685349,1675807,1889570,1480280,1735069,1812546,1487315.0,1663809,1624509,1639670,1921845,1156536,1388461,1644607
8,D,District of Columbia,1111437,1993741,1374643,1827949,1803852,1595981,1193245.0,1739748,1707823,1353449,1979708,1912654,1782169,1410183
7,D,Delaware,1330403,1268673,1706751,1403759,1441351,1300836,1762096.0,1553585,1370984,1318669,1984027,1671279,1803169,1627508
9,F,Florida,1964626,1468852,1419738,1362787,1339608,1278550,1756185.0,1818438,1198403,1497051,1131928,1107448,1407784,1170389
10,G,Georgia,1929009,1541565,1810773,1779091,1326846,1223770,1773090.0,1630325,1145473,1851245,1850111,1887157,1259353,1725470
11,H,Hawaii,1461570,1200280,1213993,1245931,1459383,1430465,1919423.0,1928416,1330509,1902816,1695126,1517184,1948108,1150882
12,I,Idaho,1353210,1438538,1739154,1541015,1122387,1772050,1335481.0,1748608,1436809,1456340,1643855,1312561,1713718,1757171
15,I,Iowa,1499269,1444576,1576367,1388924,1554813,1452911,1317983.0,1150783,1751389,1992996,1501879,1173694,1431705,1641866
13,I,Illinois,1508356,1527440,1493029,1261353,1540274,1747614,1871645.0,1658551,1422021,1751422,1696729,1915435,1645465,1583516
14,I,Indiana,1776918,1734104,1269927,1204117,1848073,1129546,1139551.0,1883976,1999102,1559924,1905760,1129794,1988394,1467614
16,K,Kansas,1509054,1290700,1522230,1532094,1104256,1863278,1949478.0,1561528,1550433,1465812,1882929,1410249,1930090,1385528
17,K,Kentucky,1813878,1448846,1800760,1250524,1137913,1911227,1301848.0,1956681,1350895,1512894,1916616,1878271,1722762,1913350
18,L,Louisiana,1584734,1110625,1868456,1751920,1233709,1920301,1185085.0,1124853,1498662,1210385,1234234,1287663,1908602,1403857
25,M,Missouri,1221316,1858368,1773451,1573967,1374863,1486197,1735099.0,1800620,1164202,1425363,1800052,1698105,1767835,1996005
22,M,Michigan,1295635,1149931,1601027,1340716,1729449,1567494,1990431.0,1575185,1267626,1274673,1709853,1815596,1965196,1646634
20,M,Maryland,1579713,1404700,1849798,1397738,1310270,1789128,1112765.0,1967225,1486246,1872327,1175819,1314343,1979529,1569566
19,M,Maine,1582720,1678622,1208496,1912040,1438549,1330014,1295877.0,1969163,1627262,1706080,1437088,1318546,1116792,1529233
21,M,Massachusetts,1647582,1686259,1620601,1777250,1531641,1380529,1978904.0,1567651,1761048,1658538,1482203,1731917,1669749,1963337
23,M,Minnesota,1729921,1675204,1903907,1561839,1985692,1148621,1328133.0,1890633,1995304,1575533,1910216,1972021,1515366,1864553
26,M,Montana,1877154,1540099,1332722,1273327,1625721,1983568,1251742.0,1592690,1350619,1520064,1185225,1465705,1110394,1125903
24,M,Mississippi,1983285,1292558,1631325,1943311,1354579,1731643,1428291.0,1568049,1383227,1629132,1988270,1907777,1649668,1991232
32,N,New York,1395149,1611371,1170675,1446810,1426941,1463171,1732098.0,1426216,1604531,1683687,1500089,1718837,1619033,1367705
29,N,New Hampshire,1419776,1854370,1195119,1990062,1645430,1286967,1762936.0,1763211,1265642,1704297,1131298,1197576,1242623,1963313
28,N,Nevada,1426117,1114500,1119707,1758830,1694526,1765826,1903270.0,1231480,1526066,1143343,1980195,1283813,1225348,1903804
30,N,New Jersey,1605532,1141514,1613550,1181452,1541327,1156804,1568034.0,1357418,1443718,1390010,1202326,1100990,1850165,1183568
33,N,North Carolina,1616742,1292223,1482792,1532347,1158716,1827420,1267737.0,1116168,1791535,1553750,1472258,1104893,1596452,1229085
34,N,North Dakota,1618807,1510193,1876940,1443172,1425030,1868788,1720352.0,1671468,1534571,1271132,1430978,1529024,1563898,1604118
31,N,New Mexico,1819239,1226057,1935991,1124400,1723493,1475985,1237704.0,1820856,1801430,1653384,1475715,1623388,1533494,1868612
27,N,Nebraska,1885081,1309769,1425527,1240465,1500594,1278272,1140598.0,1270585,1128711,1187207,1569665,1690920,1459243,1802211
36,O,Oklahoma,1173918,1334639,1663622,1798714,1312574,1708245,1256746.0,1853142,1673831,1822933,1674707,1900523,1956742,1307678
37,O,Oregon,1794912,1726665,1805445,1133510,1502242,1419251,1482786.0,1862351,1103794,1935687,1905378,1522129,1509171,1893515
35,O,Ohio,1802132,1648498,1441386,1670280,1534888,1314824,1516621.0,1511460,1585465,1887714,1227303,1840898,1880804,1573117
38,P,Pennsylvania,1320191,1446723,1218591,1122030,1971479,1563062,1274168.0,1571032,1433835,1483292,1290329,1475344,1931500,1668232
39,R,Rhode Island,1501744,1942942,1266657,1961923,1835983,1234040,1151409.0,1993136,1983569,1781016,1909119,1531212,1990412,1611730
41,S,South Dakota,1159037,1150689,1660148,1417141,1418586,1279134,1171870.0,1852424,1554782,1647245,1811156,1147488,1302834,1136443
40,S,South Carolina,1631522,1803455,1425193,1458191,1538731,1825195,1250499.0,1864685,1345102,1116203,1532332,1591735,1188417,1110655
43,T,Texas,1520591,1310777,1957713,1907326,1873544,1655483,1785986.0,1827503,1447457,1978374,1882532,1698698,1646508,1705322
42,T,Tennessee,1811867,1485909,1974179,1157059,1786132,1399191,1826406.0,1326460,1231739,1469785,1849041,1560887,1349173,1162164
44,U,Utah,1771096,1195861,1979395,1241662,1437456,1859416,1939284.0,1915865,1619186,1288285,1108281,1123353,1801019,1729273
46,V,Virginia,1134317,1163996,1891068,1853855,1708715,1197698,1803330.0,1590043,1516758,1171686,1262342,1647032,1706707,1850394
45,V,Vermont,1146902,1832249,1492704,1579265,1332048,1563537,1123567.0,1618583,1326369,1792600,1714960,1146278,1282790,1565924
48,W,West Virginia,1677347,1380662,1176100,1888948,1922085,1740826,1238174.0,1539322,1539603,1872519,1462137,1683127,1204344,1198791
50,W,Wyoming,1775190,1498098,1198212,1881688,1750527,1523124,1587602.0,1504455,1282142,1881814,1673668,1994022,1204029,1853858
49,W,Wisconsin,1788920,1518578,1289663,1436888,1251678,1721874,1980167.0,1901394,1648755,1940943,1729177,1510119,1701650,1846238
47,W,Washington,1977749,1687136,1199490,1163092,1334864,1621989,1545621.0,1555554,1179331,1150089,1775787,1273834,1387428,1377341

In [33]:
mydata["difference"] = mydata.Y2008-mydata.Y2009 #creating new column as difference of two columns
#Alternatively
mydata["difference2"] = mydata.eval("Y2008 - Y2009")
mydata.head()

,Index,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,difference,difference2
50,W,Wyoming,1775190,1498098,1198212,1881688,1750527,1523124,1587602.0,1504455,1282142,1881814,1673668,1994022,1204029,1853858,83147.0,83147.0
49,W,Wisconsin,1788920,1518578,1289663,1436888,1251678,1721874,1980167.0,1901394,1648755,1940943,1729177,1510119,1701650,1846238,78773.0,78773.0
48,W,West Virginia,1677347,1380662,1176100,1888948,1922085,1740826,1238174.0,1539322,1539603,1872519,1462137,1683127,1204344,1198791,-301148.0,-301148.0
47,W,Washington,1977749,1687136,1199490,1163092,1334864,1621989,1545621.0,1555554,1179331,1150089,1775787,1273834,1387428,1377341,-9933.0,-9933.0
46,V,Virginia,1134317,1163996,1891068,1853855,1708715,1197698,1803330.0,1590043,1516758,1171686,1262342,1647032,1706707,1850394,213287.0,213287.0

In [36]:
data = mydata.assign(ratio = (mydata.Y2008 / mydata.Y2009)) #creating new column using assign function
data.head()

,Index,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,difference,difference2,ratio
50,W,Wyoming,1775190,1498098,1198212,1881688,1750527,1523124,1587602.0,1504455,1282142,1881814,1673668,1994022,1204029,1853858,83147.0,83147.0,1.055267
49,W,Wisconsin,1788920,1518578,1289663,1436888,1251678,1721874,1980167.0,1901394,1648755,1940943,1729177,1510119,1701650,1846238,78773.0,78773.0,1.041429
48,W,West Virginia,1677347,1380662,1176100,1888948,1922085,1740826,1238174.0,1539322,1539603,1872519,1462137,1683127,1204344,1198791,-301148.0,-301148.0,0.804363
47,W,Washington,1977749,1687136,1199490,1163092,1334864,1621989,1545621.0,1555554,1179331,1150089,1775787,1273834,1387428,1377341,-9933.0,-9933.0,0.993614
46,V,Virginia,1134317,1163996,1891068,1853855,1708715,1197698,1803330.0,1590043,1516758,1171686,1262342,1647032,1706707,1850394,213287.0,213287.0,1.134139

In [ ]:
mydata.describe() #for numeric variables

,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,difference,difference2
count,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,51.000000,51.000000
mean,1.566034e+06,1.509193e+06,1.540555e+06,1.522064e+06,1.530969e+06,1.553219e+06,1.538398e+06,1.658519e+06,1.504108e+06,1.574968e+06,1.591135e+06,1.530078e+06,1.583360e+06,1.588297e+06,-120121.352941,-120121.352941
std,2.464425e+05,2.641092e+05,2.813872e+05,2.671748e+05,2.505603e+05,2.539575e+05,2.958132e+05,2.361854e+05,2.400771e+05,2.657216e+05,2.837675e+05,2.827299e+05,2.601554e+05,2.743807e+05,376427.448530,376427.448530
min,1.111437e+06,1.110625e+06,1.118631e+06,1.122030e+06,1.102568e+06,1.109382e+06,1.112765e+06,1.116168e+06,1.103794e+06,1.116203e+06,1.108281e+06,1.100990e+06,1.110394e+06,1.110655e+06,-854460.000000,-854460.000000
25%,1.374180e+06,1.292390e+06,1.268292e+06,1.267340e+06,1.337236e+06,1.322419e+06,1.254244e+06,1.553958e+06,1.328439e+06,1.371730e+06,1.360654e+06,1.285738e+06,1.385703e+06,1.372523e+06,-427001.500000,-427001.500000
50%,1.584734e+06,1.485909e+06,1.522230e+06,1.480280e+06,1.531641e+06,1.563062e+06,1.545621e+06,1.658551e+06,1.498662e+06,1.575533e+06,1.643855e+06,1.531212e+06,1.580394e+06,1.627508e+06,-9933.000000,-9933.000000
75%,1.776054e+06,1.686698e+06,1.808109e+06,1.778170e+06,1.732259e+06,1.780589e+06,1.779538e+06,1.857746e+06,1.639186e+06,1.807766e+06,1.866322e+06,1.725377e+06,1.791594e+06,1.848316e+06,147167.000000,147167.000000
max,1.983285e+06,1.994927e+06,1.979395e+06,1.990062e+06,1.985692e+06,1.983568e+06,1.990431e+06,1.993136e+06,1.999102e+06,1.992996e+06,1.988270e+06,1.994022e+06,1.990412e+06,1.996005e+06,671790.000000,671790.000000

In [38]:
mydata.describe(include = ['object']) #Only for strings / objects

       Index    State
count     51       51
unique    19       51
top        M  Wyoming
freq       8        1

In [ ]:
# particular column(s)
mydata.Y2008.mean()
mydata.Y2008.median()
mydata.Y2008.min()
mydata.loc[:,["Y2002","Y2008"]].max()

Y2002    1983285.0
Y2008    1990431.0
dtype: float64